name: pytest-test

on:
  workflow_dispatch:

jobs:
  pytest-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check Repo...
      uses: actions/checkout@v5

    - name: Set up Python...
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Setup requirements...
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests...
      run: |
        source .venv/bin/activate
        python -m pytest
